- name: Install Kubernetes master components
  shell: |
    kubeadm init --config=/home/ubuntu/kubeadm-config.yaml \
      --upload-certs \
      --v=5
  args:
    creates: /etc/kubernetes/admin.conf

- name: Copy kube config to user dir
  shell: |
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config
