---
- name: Deploy sample application
  hosts: master
  become: yes
  tasks:

    - name: Copy flannel.yaml to master node
      copy:
        src: ../files/flannel.yaml
        dest: /home/ubuntu/flannel.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Deploy flannel network plugin
      command: kubectl apply -f /home/ubuntu/flannel.yaml
      become: false
