- name: Install Docker dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker.io
    - containerd
    - runc
  become: true

- name: Enable and start docker
  service:
    name: docker
    enabled: yes
    state: started
